=== Module Codage API

==== Description

////
Module d'origine, a été merge avec tout ce qui comprend les autres aspects de navigation dans le module moduleCodaNavigation
////

Ce module consiste à gérer :

* la demande et la récupération d'itinéraire via l'API de Google Maps : cette demande a lieu au début de la navigation, en cas de décision de l'utilisateur d'atteindre un Point d'Intérêt, ou en cas de détection de changement d'itinéraire.
* le  _geocoding_ (pour récupérer les coordonnées à partir de l'adresse saisie par l'utilisateur dans le champ "destination" par exemple), et le _reverse geocoding_ (pour récupérer l'adresse correspondant à la position actuelle de l'utilisateur, pour l'adresse de départ, et pour vérifier que l'utilisateur est bien sur l'itinéraire)
* la recherche et la suggestion d'adresses lorsque l'utilisateur commence à la saisir
* la recherche de Points d'Intérêts à proximité d'un itinéraire


==== Avancement

Nous avons défini le fonctionnement de l'outil de dialogue avec l'API:

AVANT :

- demande d'itinéraire : départ - arrivée - POI
	-- géolocalisation
	-- récupération d'adresse avec l'API de Gmaps
	-- recherche d'adresse avec l'API de Gmaps
- Demande de l'itinéraire à l'API
- Stockage de la liste des virages retournée par l'API
- Demande des POI à proximité de l'itinéraire à l'API
- Demande des POI à proximité de l'itinéraire à la BDD locale

PENDANT :

- vérification de la position
- récupération de l'adresse avec l'API de Gmaps
- vérification si la position est sur l'itinéraire
	- si non : recalcul itinéraire
	- recalcul POI
- si POI près (soit à vol d'oiseau, dans ce cas pas besoin d'API, soit par temps de transports, dans ce cas re-API), vibration
	- si utilisateur accepte, recalcul itinéraire
- si virage proche (à vol d'oiseau cette fois), vibration

HORS ITINERAIRE :
- utilisation de l'API pour la recherche de POI/d'adresse rajoutées à la main dans la BDD locale

https://developers.google.com/maps/documentation/utilities/polylinealgorithm

==== Bibliographie spécifique
